FROM node:16-alpine AS development
WORKDIR /usr/local/apps/secondary

COPY package.json ./
RUN npm install && npm cache clean --force

WORKDIR /usr/local/apps/secondary/dev
COPY . .


EXPOSE 10000

CMD ["npm", "run", "start:dev"]